# Generated by Django 6.0 on 2025-12-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='URL slug (auto-generated)', max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Category description for SEO', verbose_name='Description')),
                ('language', models.CharField(choices=[('en', 'English'), ('fi', 'Finnish'), ('et', 'Estonian')], default='en', help_text='Language for this category', max_length=2, verbose_name='Language')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['language', 'order', 'name'],
                'indexes': [models.Index(fields=['language', 'slug'], name='blog_catego_languag_ccca3d_idx'), models.Index(fields=['language', 'order'], name='blog_catego_languag_d4442c_idx')],
                'constraints': [models.UniqueConstraint(fields=('language', 'slug'), name='unique_category_slug_per_language')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL slug (auto-generated)', max_length=255, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for listings (max 300 chars)', max_length=300, verbose_name='Excerpt')),
                ('content', models.TextField(help_text='Article content in Markdown format', verbose_name='Content')),
                ('article_type', models.CharField(choices=[('guide', 'Ultimate Guide'), ('post', 'Blog Post'), ('quick', 'Quick Read')], default='post', help_text='Type of content', max_length=20, verbose_name='Article type')),
                ('language', models.CharField(choices=[('en', 'English'), ('fi', 'Finnish'), ('et', 'Estonian')], db_index=True, default='en', max_length=2, verbose_name='Language')),
                ('featured_image', models.ImageField(blank=True, help_text='Main article image (1200x630px recommended)', upload_to='blog/featured/%Y/%m/', verbose_name='Featured image')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Descriptive alt text for accessibility', max_length=200, verbose_name='Image alt text')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Schedule publication (leave blank for immediate)', null=True, verbose_name='Publish date')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars, auto-generated from excerpt if blank)', max_length=160, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, verbose_name='Meta keywords')),
                ('author_name', models.CharField(default='Winter Swim Team', max_length=100, verbose_name='Author name')),
                ('reading_time_minutes', models.PositiveIntegerField(default=0, help_text='Auto-calculated from content length', verbose_name='Reading time (minutes)')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of page views', verbose_name='View count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='blog_articl_status_47bfec_idx'), models.Index(fields=['language', 'status', '-published_at'], name='blog_articl_languag_730904_idx'), models.Index(fields=['category', 'status', '-published_at'], name='blog_articl_categor_a1ad8f_idx'), models.Index(fields=['article_type', 'status'], name='blog_articl_article_bc14eb_idx'), models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx')],
                'constraints': [models.UniqueConstraint(fields=('language', 'slug'), name='unique_article_slug_per_language')],
            },
        ),
    ]
