# Generated by manual migration
import re
from django.db import migrations
from django.utils.text import slugify


def remove_uuid_from_category_slugs(apps, schema_editor):
    """
    Remove UUID suffix from existing category slugs.

    Converts slugs from format 'category-name-uuid' to 'category-name'.
    """
    Category = apps.get_model('blog', 'Category')

    for category in Category.objects.all():
        # Match pattern: base-slug-uuid (where uuid is 8 hex chars)
        # Example: "safety-tips-3c13e713" -> "safety-tips"
        match = re.match(r'^(.+)-([0-9a-f]{8})$', category.slug)

        if match:
            # Extract the base slug without UUID
            new_slug = match.group(1)

            # Update the category
            category.slug = new_slug
            category.save(update_fields=['slug'])


def add_uuid_to_category_slugs(apps, schema_editor):
    """
    Reverse migration: Add UUID suffix back to category slugs.

    This is a safeguard in case we need to rollback.
    """
    import uuid
    Category = apps.get_model('blog', 'Category')

    for category in Category.objects.all():
        # Only add UUID if slug doesn't already have one
        if not re.match(r'^.+-[0-9a-f]{8}$', category.slug):
            uuid_part = str(uuid.uuid4()).split('-')[0]
            category.slug = f"{category.slug}-{uuid_part}"
            category.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            remove_uuid_from_category_slugs,
            reverse_code=add_uuid_to_category_slugs
        ),
    ]
