# Generated by Django 6.0 on 2025-12-09 15:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import infrastructure.storage.backends
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the swimming location', max_length=200, verbose_name='Name')),
                ('name_en', models.CharField(help_text='Name of the swimming location', max_length=200, null=True, verbose_name='Name')),
                ('name_fi', models.CharField(help_text='Name of the swimming location', max_length=200, null=True, verbose_name='Name')),
                ('name_et', models.CharField(help_text='Name of the swimming location', max_length=200, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the location', verbose_name='Description')),
                ('description_en', models.TextField(blank=True, help_text='Detailed description of the location', null=True, verbose_name='Description')),
                ('description_fi', models.TextField(blank=True, help_text='Detailed description of the location', null=True, verbose_name='Description')),
                ('description_et', models.TextField(blank=True, help_text='Detailed description of the location', null=True, verbose_name='Description')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic coordinates', srid=4326, verbose_name='Location')),
                ('address', models.CharField(blank=True, help_text='Human-readable address', max_length=500, verbose_name='Address')),
                ('location_type', models.CharField(choices=[('wild', 'Wild spot'), ('commercial', 'Commercial facility'), ('club', 'Swimming club'), ('public', 'Public facility')], default='wild', max_length=20, verbose_name='Location type')),
                ('facilities', models.JSONField(blank=True, default=list, help_text='Available facilities (sauna, changing rooms, etc.)', verbose_name='Facilities')),
                ('access_instructions', models.TextField(blank=True, help_text='How to access this location', verbose_name='Access instructions')),
                ('access_instructions_en', models.TextField(blank=True, help_text='How to access this location', null=True, verbose_name='Access instructions')),
                ('access_instructions_fi', models.TextField(blank=True, help_text='How to access this location', null=True, verbose_name='Access instructions')),
                ('access_instructions_et', models.TextField(blank=True, help_text='How to access this location', null=True, verbose_name='Access instructions')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('is_free', models.BooleanField(default=True, help_text='Whether access is free', verbose_name='Free access')),
                ('pricing_details', models.TextField(blank=True, help_text='Details about pricing if not free', verbose_name='Pricing details')),
                ('pricing_details_en', models.TextField(blank=True, help_text='Details about pricing if not free', null=True, verbose_name='Pricing details')),
                ('pricing_details_fi', models.TextField(blank=True, help_text='Details about pricing if not free', null=True, verbose_name='Pricing details')),
                ('pricing_details_et', models.TextField(blank=True, help_text='Details about pricing if not free', null=True, verbose_name='Pricing details')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this location has been approved by moderators', verbose_name='Approved')),
                ('submitted_by_name', models.CharField(blank=True, help_text='Name of person who submitted this location', max_length=200, verbose_name='Submitted by')),
                ('submitted_by_email', models.EmailField(blank=True, help_text='Email of person who submitted (for follow-up)', max_length=254, verbose_name='Submitter email')),
                ('moderation_notes', models.TextField(blank=True, help_text='Internal notes for moderators', verbose_name='Moderation notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_approved', '-created_at'], name='locations_l_is_appr_bfc24e_idx'), models.Index(fields=['location_type'], name='locations_l_locatio_aa6df5_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=infrastructure.storage.backends.get_photo_storage, upload_to='location_photos/%Y/%m/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which photos are displayed', verbose_name='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='locations.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Location photo',
                'verbose_name_plural': 'Location photos',
                'ordering': ['order', '-uploaded_at'],
                'indexes': [models.Index(fields=['location', 'order'], name='locations_l_locatio_1b00f5_idx')],
            },
        ),
    ]
