# Generated by Django 6.0 on 2025-12-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL slug (auto-generated)', max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
