# Generated by Django 6.0 on 2025-12-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='location',
            name='location_search_en_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_search_fi_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_search_et_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_address_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_list_query_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_spatial_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_type_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_approved_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_name_en_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_name_fi_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_name_et_trgm_idx',
        ),
        migrations.RemoveField(
            model_name='location',
            name='search_vector_en',
        ),
        migrations.RemoveField(
            model_name='location',
            name='search_vector_et',
        ),
        migrations.RemoveField(
            model_name='location',
            name='search_vector_fi',
        ),
    ]
