# Generated by Django 6.0 on 2025-12-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_location_location_search_en_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, help_text='City where the location is located', max_length=200, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='location',
            name='city_slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly city slug (auto-generated)', max_length=220, verbose_name='City slug'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, help_text='Country where the location is located', max_length=200, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='location',
            name='country_slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly country slug (auto-generated)', max_length=220, verbose_name='Country slug'),
        ),
    ]
