# Generated by Django 6.0 on 2025-12-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_location_city_location_city_slug_location_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city_en',
            field=models.CharField(blank=True, help_text='City where the location is located', max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='location',
            name='city_et',
            field=models.CharField(blank=True, help_text='City where the location is located', max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='location',
            name='city_fi',
            field=models.CharField(blank=True, help_text='City where the location is located', max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='location',
            name='country_en',
            field=models.CharField(blank=True, help_text='Country where the location is located', max_length=200, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='location',
            name='country_et',
            field=models.CharField(blank=True, help_text='Country where the location is located', max_length=200, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='location',
            name='country_fi',
            field=models.CharField(blank=True, help_text='Country where the location is located', max_length=200, null=True, verbose_name='Country'),
        ),
    ]
