# Generated by Django 6.0 on 2026-01-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_location_city_en_location_city_et_location_city_fi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='location',
            name='submitted_by_email',
            field=models.EmailField(blank=True, help_text='Email of person who submitted (for follow-up)', max_length=254, null=True, verbose_name='Submitter email'),
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
